#!/bin/sh
# Code sign the application bundle on Apple systems.
if [[ -z "${DEPLOY_ENV}" ]]; then
	>&2 echo "Warning: Skipping code signing because \$MAC_DEVELOPER_IDENTITY is not defined."
else
	BUNDLE=`./abspath $1`
	codesign --force --sign "$MAC_DEVELOPER_IDENTITY" -v --deep "$BUNDLE"
	exit $?
fi
